### PR TITLE
Create api

### PR DESCRIPTION
**Pull request by cabutler10**
please keep the format of the forecast.json and remove the eisbach.json so we only have to make one api call. for current section, please give me 9 values in total, taken every two hours (i don't think we really need the model to run every single hour, every other hour would be fine).
 "current": {
    "temp": [58, 60, 69, 74, 77, 68, 65, 64, 65],
    "waterTemp": [15.8, 15.7, 15.4, 15.1, 15.2, 14.9, 14.8, 14.7, 14.7],

let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by PaVrat** [comment]
> u

Why do we need only 9 values? and do we need also the air temperature for each 2 hours? Because for that I have currently no data available

**Comment by cabutler10** [comment]
because i want a to make a chart that looks like google weather and it only needs 9 data points. my thought was you can pull the current temp and add it to an array, then run the script every 2 hours and always add the latest current water temp and air temp. The array should not have more than 9 data points. (if len(arr) > 9, arr.pop(0) then arr.append(new value) ). does that make sense?

**Comment by PaVrat** [comment]
Hmmm...okay. I am currently not directly storing the data of the eisbach. Just crawling the data from the website and directly write from python to the json file. I have to implement to use the json as storage. One issue here is that we then have to ensure that it is really updating every 2 hours. 

BTW in some cases we will have Nan values in the array, because the sensor is not always delivering a value. Is this a problem?

**Comment by cabutler10** [comment]
before I had it call for the previous value or the one before that, usually 2 back solves the problem

**Comment by cabutler10** [comment]
you also no longer need the json, you can write a dict directly to the api with jsonify(dict). 
so you make your create_model file into a function and then call that from the flask app.

**Pull request merged**
